create type eye_color as enum ('BR', 'BL', 'GR');

create table person
(
    person_id   smallint,
    fname       varchar(20),
    lname       varchar(20),
    eye_color   eye_color,
    birth_date  date,
    street      varchar(30),
    city        varchar(20),
    state       varchar(20),
    country     varchar(20),
    postal_code varchar(20),
    constraint pk_person primary key (person_id)
);

select *
from person;

SELECT typname
FROM pg_type
WHERE typnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public');

create table favorite_food
(
    person_id smallint,
    food      varchar(20),
    constraint pk_favorite_food primary key (person_id, food),
    constraint fk_fav_food_person_id foreign key (person_id) references person (person_id)
);

alter table person
    alter column person_id add generated by default as identity;

insert into person (fname, lname, eye_color, birth_date)
values ('William', 'Turner', 'BR', '1972-05-27');

select person_id, fname, lname, birth_date from person;